#!/usr/bin/env python3
"""Step 5 finite-carrier diagnostic for the bounded P* coupling design."""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np


ARTIFACT_DIR = Path(__file__).resolve().parent


def adequacy_residual(native: np.ndarray, dissolving: np.ndarray) -> dict:
    """Compute Xi = K_DD - K_DL K_LL^dagger K_LD for C = I."""
    k_ll = native @ native.T
    k_dd = dissolving @ dissolving.T
    k_dl = dissolving @ native.T
    xi = k_dd - k_dl @ np.linalg.pinv(k_ll, rcond=1e-12) @ k_dl.T
    xi = 0.5 * (xi + xi.T)
    eigvals = np.linalg.eigvalsh(xi)
    raw = float(np.trace(xi))
    denom = float(np.trace(k_dd))
    normalized = float(raw / denom) if denom > 0 else float("nan")
    return {
        "K_DD": k_dd,
        "Xi": xi,
        "eigvals": eigvals,
        "raw_trace": raw,
        "normalized_trace": normalized,
        "trace_K_DD": denom,
    }


def level_matrices(region_count: int) -> dict:
    """Declare bounded G_v1 P* source rows and generated bridge targets."""
    if region_count < 2:
        raise ValueError("region_count must be at least 2")

    # Source rows allowed by bounded G_v1: a shared area/geometry currency u_i
    # and one route-holonomy/RG row v.  Two residual coordinates are kept
    # outside the native lens: HED-AS boundary/continuum and triple package.
    dim = region_count + 3
    u_start = 0
    v_idx = region_count
    residual_ha_idx = region_count + 1
    residual_triple_idx = region_count + 2

    basis = [f"pstar_shared_area_geometry_currency_{i}" for i in range(region_count)]
    basis += [
        "pstar_route_holonomy_rg_source",
        "residual_HED_AS_boundary_continuum",
        "residual_triple_joint_package",
    ]

    pstar_rows = []
    pstar_names = []
    for i in range(region_count):
        row = np.zeros(dim)
        row[u_start + i] = 1.0
        pstar_rows.append(row)
        pstar_names.append(f"Pstar_shared_currency_{i}")

    v_row = np.zeros(dim)
    v_row[v_idx] = 1.0
    pstar_rows.append(v_row)
    pstar_names.append("Pstar_route_holonomy_rg")
    pstar_native = np.vstack(pstar_rows)

    u_avg = np.zeros(dim)
    u_avg[:region_count] = 1.0 / np.sqrt(region_count)

    area_rows = []
    area_names = []
    for i in range(region_count):
        row = np.zeros(dim)
        row[i] = 1.0 / np.sqrt(region_count)
        area_rows.append(row)
        area_names.append(f"generated_area_shadow_{i}")
    d_area = np.vstack(area_rows)

    d_amplitude = np.vstack([u_avg])
    d_p3 = np.vstack([v_row])

    # Bridge rows generated by P*: they are shadows of the allowed P* source
    # rows, not free compatibility facts inserted into the native lens.
    bridge_hl = np.vstack([u_avg])
    bridge_la = np.vstack([v_row])

    # Residual bridge rows outside bounded G_v1.
    bridge_ha = np.zeros(dim)
    bridge_ha[residual_ha_idx] = 1.0
    bridge_triple = np.zeros(dim)
    bridge_triple[residual_triple_idx] = 1.0
    d_bridge_ha = np.vstack([bridge_ha])
    d_bridge_triple = np.vstack([bridge_triple])

    d_all_bridges = np.vstack([bridge_hl, bridge_la, d_bridge_ha, d_bridge_triple])
    d_coupled = np.vstack([d_area, d_amplitude, d_p3, d_all_bridges])

    # Rejected controls.
    overread_native = np.vstack([pstar_native, d_bridge_ha, d_bridge_triple])

    return {
        "basis": basis,
        "pstar_native": pstar_native,
        "pstar_names": pstar_names,
        "d_area": d_area,
        "d_amplitude": d_amplitude,
        "d_p3": d_p3,
        "bridge_HED_LQG": bridge_hl,
        "bridge_LQG_AS": bridge_la,
        "bridge_HED_AS": d_bridge_ha,
        "bridge_triple": d_bridge_triple,
        "d_all_bridges": d_all_bridges,
        "d_coupled": d_coupled,
        "overread_native": overread_native,
        "generation_maps": {
            "Bridge_HED_LQG_area_geometry": "generated_area_geometry_shadow = average(Pstar_shared_currency_i)",
            "Bridge_LQG_AS_discrete_continuum": "generated_route_shadow = Pstar_route_holonomy_rg",
            "Bridge_HED_AS_boundary_continuum": "not generated in G_v1",
            "Bridge_triple_joint_package": "not generated in G_v1",
        },
    }


def block_summary(native: np.ndarray, dissolving: np.ndarray) -> dict:
    block = adequacy_residual(native, dissolving)
    return {
        "raw_trace": block["raw_trace"],
        "normalized_trace": block["normalized_trace"],
        "trace_K_DD": block["trace_K_DD"],
        "min_eigenvalue": float(np.min(block["eigvals"])),
        "max_eigenvalue": float(np.max(block["eigvals"])),
        "Xi_matrix": np.round(block["Xi"], 10).tolist(),
    }


def summarize_level(region_count: int) -> dict:
    data = level_matrices(region_count)
    native = data["pstar_native"]

    bridge_blocks = {
        "Bridge_HED_LQG_area_geometry": block_summary(native, data["bridge_HED_LQG"]),
        "Bridge_LQG_AS_discrete_continuum": block_summary(native, data["bridge_LQG_AS"]),
        "Bridge_HED_AS_boundary_continuum": block_summary(native, data["bridge_HED_AS"]),
        "Bridge_triple_joint_package": block_summary(native, data["bridge_triple"]),
    }

    sectors = {
        "area_shadow_sector": block_summary(native, data["d_area"]),
        "amplitude_geometry_sector": block_summary(native, data["d_amplitude"]),
        "p3_route_sector": block_summary(native, data["d_p3"]),
    }

    all_bridges = block_summary(native, data["d_all_bridges"])
    coupled = block_summary(native, data["d_coupled"])
    overread = block_summary(data["overread_native"], data["d_coupled"])

    return {
        "region_count": region_count,
        "carrier_dimension": len(data["basis"]),
        "basis": data["basis"],
        "pstar_native_probe_names": data["pstar_names"],
        "generation_maps": data["generation_maps"],
        "sector_results": sectors,
        "bridge_results": bridge_blocks,
        "all_bridges": all_bridges,
        "coupled_joint": coupled,
        "target_equivalent_overread_control": {
            "raw_trace": overread["raw_trace"],
            "normalized_trace": overread["normalized_trace"],
            "flag": "zero only after adding residual bridge rows to native lens",
        },
        "no_overread_check": {
            "residual_bridge_rows_used_as_native_probes": False,
            "bridge_rows_inserted_as_free_source_facts": False,
            "closed_bridges_have_generation_maps": True,
            "fixed_bulk_metric_inserted": False,
            "planck_constant_inserted": False,
            "pstar_is_not_assume_compatibility": True,
        },
    }


def main() -> None:
    levels = [2, 4]
    results = [summarize_level(level) for level in levels]

    coupled_norms = [row["coupled_joint"]["normalized_trace"] for row in results]
    coupled_raw = [row["coupled_joint"]["raw_trace"] for row in results]
    all_bridge_norms = [row["all_bridges"]["normalized_trace"] for row in results]

    payload = {
        "step": 5,
        "toy_name": "finite_pstar_bounded_coupling_design_xi_diagnostic",
        "orientation": "Mode B bounded design diagnostic for P*",
        "bounded_grammar": "G_E018_CoupledQGBridge_v1",
        "pstar_design": {
            "name": "shared_scale_currency_with_route_holonomy",
            "native_rows": "shared area/geometry currency u_i plus route holonomy/RG row v",
            "excluded_rows": [
                "Bridge_HED_AS_boundary_continuum",
                "Bridge_triple_joint_package",
            ],
        },
        "results": results,
        "refinement_stability": {
            "coupled_normalized_level_2": coupled_norms[0],
            "coupled_normalized_level_4": coupled_norms[1],
            "coupled_raw_level_2": coupled_raw[0],
            "coupled_raw_level_4": coupled_raw[1],
            "all_bridges_normalized_level_2": all_bridge_norms[0],
            "all_bridges_normalized_level_4": all_bridge_norms[1],
            "coupled_absolute_delta": float(abs(coupled_norms[1] - coupled_norms[0])),
            "all_bridges_absolute_delta": float(abs(all_bridge_norms[1] - all_bridge_norms[0])),
            "interpretation": "P* closes HED-LQG and LQG-AS bridges, but leaves HED-AS and triple package residuals",
        },
        "verdict_from_toy": "partial Mode B design in G_v1; not a full landing",
    }

    json_path = ARTIFACT_DIR / "simulation_output_step5.json"
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    csv_path = ARTIFACT_DIR / "xi_diagnostic_step5.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "level_regions",
                "carrier_dimension",
                "group",
                "name",
                "raw_trace_xi",
                "trace_kdd",
                "normalized_trace_xi",
                "status",
            ],
        )
        writer.writeheader()
        for row in results:
            for name, block in row["sector_results"].items():
                writer.writerow(
                    {
                        "level_regions": row["region_count"],
                        "carrier_dimension": row["carrier_dimension"],
                        "group": "sector",
                        "name": name,
                        "raw_trace_xi": block["raw_trace"],
                        "trace_kdd": block["trace_K_DD"],
                        "normalized_trace_xi": block["normalized_trace"],
                        "status": "closed_by_Pstar_v1",
                    }
                )
            for name, block in row["bridge_results"].items():
                closed = block["normalized_trace"] <= 1e-12
                writer.writerow(
                    {
                        "level_regions": row["region_count"],
                        "carrier_dimension": row["carrier_dimension"],
                        "group": "bridge",
                        "name": name,
                        "raw_trace_xi": block["raw_trace"],
                        "trace_kdd": block["trace_K_DD"],
                        "normalized_trace_xi": block["normalized_trace"],
                        "status": "closed_by_generation_map" if closed else "survives_G_v1",
                    }
                )
            writer.writerow(
                {
                    "level_regions": row["region_count"],
                    "carrier_dimension": row["carrier_dimension"],
                    "group": "coupled_joint",
                    "name": "all_sectors_plus_all_bridges",
                    "raw_trace_xi": row["coupled_joint"]["raw_trace"],
                    "trace_kdd": row["coupled_joint"]["trace_K_DD"],
                    "normalized_trace_xi": row["coupled_joint"]["normalized_trace"],
                    "status": "partial_residual_survives",
                }
            )

    text_path = ARTIFACT_DIR / "simulation_output_step5.txt"
    lines = [
        "Step 5 finite-carrier P* bounded design diagnostic",
        f"levels={levels}",
        f"coupled_joint_normalized_residuals={coupled_norms}",
        f"coupled_joint_raw_residuals={coupled_raw}",
        f"all_bridge_normalized_residuals={all_bridge_norms}",
        "closed_bridges=Bridge_HED_LQG_area_geometry,Bridge_LQG_AS_discrete_continuum",
        "surviving_bridges=Bridge_HED_AS_boundary_continuum,Bridge_triple_joint_package",
        "overread_control=zero only if residual bridge rows are added to native lens",
    ]
    text_path.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(json.dumps(payload["refinement_stability"], indent=2))


if __name__ == "__main__":
    main()
