#!/usr/bin/env python3
"""Step 6 finite-carrier diagnostic for bounded G_v2 boundary-flow design."""

from __future__ import annotations

import csv
import json
from pathlib import Path

import numpy as np


ARTIFACT_DIR = Path(__file__).resolve().parent


def adequacy_residual(native: np.ndarray, dissolving: np.ndarray) -> dict:
    """Compute Xi = K_DD - K_DL K_LL^dagger K_LD for C = I."""
    k_ll = native @ native.T
    k_dd = dissolving @ dissolving.T
    k_dl = dissolving @ native.T
    xi = k_dd - k_dl @ np.linalg.pinv(k_ll, rcond=1e-12) @ k_dl.T
    xi = 0.5 * (xi + xi.T)
    eigvals = np.linalg.eigvalsh(xi)
    raw = float(np.trace(xi))
    denom = float(np.trace(k_dd))
    normalized = float(raw / denom) if denom > 0 else float("nan")
    return {
        "K_DD": k_dd,
        "Xi": xi,
        "eigvals": eigvals,
        "raw_trace": raw,
        "normalized_trace": normalized,
        "trace_K_DD": denom,
    }


def block_summary(native: np.ndarray, dissolving: np.ndarray) -> dict:
    block = adequacy_residual(native, dissolving)
    return {
        "raw_trace": block["raw_trace"],
        "normalized_trace": block["normalized_trace"],
        "trace_K_DD": block["trace_K_DD"],
        "min_eigenvalue": float(np.min(block["eigvals"])),
        "max_eigenvalue": float(np.max(block["eigvals"])),
        "Xi_matrix": np.round(block["Xi"], 10).tolist(),
    }


def level_matrices(region_count: int) -> dict:
    """Declare inherited G_v1 rows plus the bounded G_v2 boundary-flow row."""
    if region_count < 2:
        raise ValueError("region_count must be at least 2")

    # Basis:
    # u_i are inherited G_v1 shared area/geometry currency rows.
    # v is the inherited G_v1 route-holonomy/RG row.
    # w is the only new G_v2 source row: a holographic-RG boundary/continuum
    # flow coordinate, motivated by the UV/IR and holographic RG import.
    # t is the triple-package residual coordinate.  It is intentionally not
    # native in G_v2 because no specific triple audit functional is declared.
    dim = region_count + 3
    v_idx = region_count
    w_idx = region_count + 1
    t_idx = region_count + 2

    basis = [f"inherited_shared_area_geometry_currency_{i}" for i in range(region_count)]
    basis += [
        "inherited_route_holonomy_rg_source",
        "gv2_holographic_rg_boundary_continuum_flow",
        "residual_triple_joint_package",
    ]

    native_rows = []
    native_names = []
    for i in range(region_count):
        row = np.zeros(dim)
        row[i] = 1.0
        native_rows.append(row)
        native_names.append(f"inherited_Pstar_shared_currency_{i}")

    v_row = np.zeros(dim)
    v_row[v_idx] = 1.0
    native_rows.append(v_row)
    native_names.append("inherited_Pstar_route_holonomy_rg")

    w_row = np.zeros(dim)
    w_row[w_idx] = 1.0
    native_rows.append(w_row)
    native_names.append("Gv2_holographic_rg_boundary_continuum_flow")

    gv2_native = np.vstack(native_rows)

    u_avg = np.zeros(dim)
    u_avg[:region_count] = 1.0 / np.sqrt(region_count)

    area_rows = []
    for i in range(region_count):
        row = np.zeros(dim)
        row[i] = 1.0 / np.sqrt(region_count)
        area_rows.append(row)
    d_area = np.vstack(area_rows)
    d_amplitude = np.vstack([u_avg])
    d_p3 = np.vstack([v_row])

    # Bridge rows.  The first two remain generated by the inherited G_v1
    # predicate.  The HED-AS bridge is generated by the new w row.  The triple
    # package row remains outside the native lens until a later grammar declares
    # a non-tautological audit functional.
    bridge_hl = np.vstack([u_avg])
    bridge_la = np.vstack([v_row])
    bridge_ha = np.vstack([w_row])
    triple_row = np.zeros(dim)
    triple_row[t_idx] = 1.0
    bridge_triple = np.vstack([triple_row])

    d_all_bridges = np.vstack([bridge_hl, bridge_la, bridge_ha, bridge_triple])
    d_surviving_step5 = np.vstack([bridge_ha, bridge_triple])
    d_coupled = np.vstack([d_area, d_amplitude, d_p3, d_all_bridges])

    # Rejected control: adding the triple residual coordinate as a native source
    # makes the diagnostic zero, but that is not a generated G_v2 result.
    overread_native = np.vstack([gv2_native, bridge_triple])

    return {
        "basis": basis,
        "gv2_native": gv2_native,
        "native_names": native_names,
        "d_area": d_area,
        "d_amplitude": d_amplitude,
        "d_p3": d_p3,
        "bridge_HED_LQG": bridge_hl,
        "bridge_LQG_AS": bridge_la,
        "bridge_HED_AS": bridge_ha,
        "bridge_triple": bridge_triple,
        "d_all_bridges": d_all_bridges,
        "d_surviving_step5": d_surviving_step5,
        "d_coupled": d_coupled,
        "overread_native": overread_native,
        "generation_maps": {
            "Bridge_HED_LQG_area_geometry": "inherited from G_v1: average(u_i)",
            "Bridge_LQG_AS_discrete_continuum": "inherited from G_v1: route row v",
            "Bridge_HED_AS_boundary_continuum": "generated by G_v2 holographic-RG flow row w",
            "Bridge_triple_joint_package": "not generated in G_v2",
        },
    }


def summarize_level(region_count: int) -> dict:
    data = level_matrices(region_count)
    native = data["gv2_native"]

    bridge_blocks = {
        "Bridge_HED_LQG_area_geometry": block_summary(native, data["bridge_HED_LQG"]),
        "Bridge_LQG_AS_discrete_continuum": block_summary(native, data["bridge_LQG_AS"]),
        "Bridge_HED_AS_boundary_continuum": block_summary(native, data["bridge_HED_AS"]),
        "Bridge_triple_joint_package": block_summary(native, data["bridge_triple"]),
    }

    sectors = {
        "area_shadow_sector": block_summary(native, data["d_area"]),
        "amplitude_geometry_sector": block_summary(native, data["d_amplitude"]),
        "p3_route_sector": block_summary(native, data["d_p3"]),
    }

    surviving_step5 = block_summary(native, data["d_surviving_step5"])
    all_bridges = block_summary(native, data["d_all_bridges"])
    coupled = block_summary(native, data["d_coupled"])
    overread = block_summary(data["overread_native"], data["d_coupled"])

    return {
        "region_count": region_count,
        "carrier_dimension": len(data["basis"]),
        "basis": data["basis"],
        "gv2_native_probe_names": data["native_names"],
        "generation_maps": data["generation_maps"],
        "sector_results": sectors,
        "bridge_results": bridge_blocks,
        "surviving_step5_bridge_pair": surviving_step5,
        "all_bridges": all_bridges,
        "coupled_joint": coupled,
        "target_equivalent_overread_control": {
            "raw_trace": overread["raw_trace"],
            "normalized_trace": overread["normalized_trace"],
            "flag": "zero only after adding the triple residual row to the native lens",
        },
        "no_overread_check": {
            "step5_closed_pairwise_bridges_reopened": False,
            "residual_bridge_rows_used_as_native_probes": False,
            "bridge_rows_inserted_as_free_source_facts": False,
            "triple_row_inserted_as_native_probe": False,
            "boundary_continuum_has_generation_map": True,
            "triple_has_generation_map": False,
            "fixed_bulk_metric_inserted": False,
            "planck_constant_inserted": False,
            "gv2_is_not_primitive_global_compatibility": True,
        },
    }


def main() -> None:
    levels = [2, 4]
    results = [summarize_level(level) for level in levels]

    coupled_norms = [row["coupled_joint"]["normalized_trace"] for row in results]
    coupled_raw = [row["coupled_joint"]["raw_trace"] for row in results]
    all_bridge_norms = [row["all_bridges"]["normalized_trace"] for row in results]
    step5_survivor_norms = [
        row["surviving_step5_bridge_pair"]["normalized_trace"] for row in results
    ]

    payload = {
        "step": 6,
        "toy_name": "finite_gv2_boundary_continuum_design_xi_diagnostic",
        "orientation": "Mode B bounded design diagnostic for G_v2",
        "bounded_grammar": "G_E018_BoundaryContinuumTripleBridge_v2",
        "gv2_design": {
            "name": "holographic_rg_boundary_flow_extension",
            "inherited_native_rows": "G_v1 shared area/geometry currency u_i plus route-holonomy row v",
            "new_native_rows": "one holographic-RG boundary/continuum flow row w",
            "excluded_rows": ["Bridge_triple_joint_package"],
        },
        "source_anchor": {
            "boundary_flow_atom": "UV/IR plus holographic RG row: radial cutoff / boundary RG scale map in an AdS-like state class",
            "scope": "design-coherence diagnostic under holographic RG assumptions, not a physics proof",
        },
        "results": results,
        "refinement_stability": {
            "coupled_normalized_level_2": coupled_norms[0],
            "coupled_normalized_level_4": coupled_norms[1],
            "coupled_raw_level_2": coupled_raw[0],
            "coupled_raw_level_4": coupled_raw[1],
            "all_bridges_normalized_level_2": all_bridge_norms[0],
            "all_bridges_normalized_level_4": all_bridge_norms[1],
            "step5_survivor_pair_normalized_level_2": step5_survivor_norms[0],
            "step5_survivor_pair_normalized_level_4": step5_survivor_norms[1],
            "coupled_absolute_delta": float(abs(coupled_norms[1] - coupled_norms[0])),
            "all_bridges_absolute_delta": float(abs(all_bridge_norms[1] - all_bridge_norms[0])),
            "step5_survivor_pair_absolute_delta": float(
                abs(step5_survivor_norms[1] - step5_survivor_norms[0])
            ),
            "interpretation": (
                "G_v2 generates the HED-AS boundary/continuum bridge while the "
                "triple package remains residual."
            ),
        },
        "verdict_from_toy": "candidate G_v2 partial design; next grammar must address triple audit package",
    }

    json_path = ARTIFACT_DIR / "simulation_output_step6.json"
    json_path.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    csv_path = ARTIFACT_DIR / "xi_diagnostic_step6.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(
            handle,
            fieldnames=[
                "level_regions",
                "carrier_dimension",
                "group",
                "name",
                "raw_trace_xi",
                "trace_kdd",
                "normalized_trace_xi",
                "status",
            ],
        )
        writer.writeheader()
        for row in results:
            for name, block in row["sector_results"].items():
                writer.writerow(
                    {
                        "level_regions": row["region_count"],
                        "carrier_dimension": row["carrier_dimension"],
                        "group": "sector",
                        "name": name,
                        "raw_trace_xi": block["raw_trace"],
                        "trace_kdd": block["trace_K_DD"],
                        "normalized_trace_xi": block["normalized_trace"],
                        "status": "closed_by_inherited_or_gv2_native_rows",
                    }
                )
            for name, block in row["bridge_results"].items():
                closed = block["normalized_trace"] <= 1e-12
                status = "closed_by_generation" if closed else "survives_G_v2"
                writer.writerow(
                    {
                        "level_regions": row["region_count"],
                        "carrier_dimension": row["carrier_dimension"],
                        "group": "bridge",
                        "name": name,
                        "raw_trace_xi": block["raw_trace"],
                        "trace_kdd": block["trace_K_DD"],
                        "normalized_trace_xi": block["normalized_trace"],
                        "status": status,
                    }
                )
            for group_name, block in [
                ("surviving_step5_bridge_pair", row["surviving_step5_bridge_pair"]),
                ("all_bridges", row["all_bridges"]),
                ("coupled_joint", row["coupled_joint"]),
            ]:
                writer.writerow(
                    {
                        "level_regions": row["region_count"],
                        "carrier_dimension": row["carrier_dimension"],
                        "group": "aggregate",
                        "name": group_name,
                        "raw_trace_xi": block["raw_trace"],
                        "trace_kdd": block["trace_K_DD"],
                        "normalized_trace_xi": block["normalized_trace"],
                        "status": "diagnostic_aggregate",
                    }
                )

    txt_lines = [
        "Step 6 finite G_v2 Xi diagnostic",
        "G_v2 native lens: inherited u_i and v, plus holographic-RG row w.",
        "Closed by generation: HED-LQG, LQG-AS, HED-AS boundary/continuum.",
        "Survives: triple shared completion/audit package.",
    ]
    for result in results:
        txt_lines.append(
            "r={r}: coupled raw Xi={raw}, normalized Xi={norm}; all-bridge normalized Xi={bnorm}; Step-5 survivor-pair normalized Xi={snorm}".format(
                r=result["region_count"],
                raw=result["coupled_joint"]["raw_trace"],
                norm=result["coupled_joint"]["normalized_trace"],
                bnorm=result["all_bridges"]["normalized_trace"],
                snorm=result["surviving_step5_bridge_pair"]["normalized_trace"],
            )
        )
    txt_lines.append("Rejected control: adding the triple residual as native gives zero residual but is not generation.")
    (ARTIFACT_DIR / "simulation_output_step6.txt").write_text(
        "\n".join(txt_lines) + "\n", encoding="utf-8"
    )


if __name__ == "__main__":
    main()
